### ISSUE TITLE
npm build script fails on master.

### ISSUE THREAD

**Issue by azizur** [quran/quran.com-frontend#196]
npm build script fails on master with following errors.
```
$ npm run build

> quran@0.0.0 build /{path-to-repo}/quran.com-frontend
> node ./node_modules/webpack/bin/webpack.js --verbose --colors --display-error-details --config webpack.prod.config.js

Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Hash: 7cf0928273875d7a3577
Version: webpack 1.12.14
Time: 7078ms
   [0] multi main 40 bytes {0} [built] [1 error]
    + 9 hidden modules

ERROR in ./client.js
Module build failed: ReferenceError: [BABEL] /{path-to-repo}/quran.com-frontend/client.js: Unknown option: base.stage
    at Logger.error (/{path-to-repo}/quran.com-frontend/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/{path-to-repo}/quran.com-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:18)
    at OptionManager.init (/{path-to-repo}/quran.com-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:486:10)
    at File.initOptions (/{path-to-repo}/quran.com-frontend/node_modules/babel-core/lib/transformation/file/index.js:211:75)
    at new File (/{path-to-repo}/quran.com-frontend/node_modules/babel-core/lib/transformation/file/index.js:129:22)
    at Pipeline.transform (/{path-to-repo}/quran.com-frontend/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
    at transpile (/{path-to-repo}/quran.com-frontend/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/{path-to-repo}/quran.com-frontend/node_modules/babel-loader/index.js:88:12)
 @ multi main
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

**Comment by ahmedre** [comment]
@mmahalwy according to [this](http://stackoverflow.com/questions/33630696/react-0-14-error-module-build-failed-referenceerror-babel-node-modules), we need to install one of the presets, and then add a `.babelrc` file (ex `echo '{ "presets": ["es2015"] }' > .babelrc`).

**Comment by ahmedre** [comment]
you can unblock yourself temporarily by building the production version since it does't have this issue.

**Comment by mmahalwy** [comment]
@azizur that must mean you have babel 6 which I haven't ported our project to just yet. Hence why .babelrc, which babel 6 picks up and now supports/enforces. See what version of babel you downloaded?

**Comment by mmahalwy** [comment]
I'd suggest not using master just yet. The babel problem is where I last left off. Use the rewrite branch. I need help there

**Comment by azizur** [comment]
In that case I should close this issue.

**Comment by mmahalwy** [comment]
Master should be stable
